// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/ai.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatToken_Type int32

const (
	ChatToken_GENERATION_START ChatToken_Type = 0
	ChatToken_TOKEN            ChatToken_Type = 1
	ChatToken_THOUGHT          ChatToken_Type = 2
	ChatToken_COMPLETE         ChatToken_Type = 3
	ChatToken_ERROR            ChatToken_Type = 4
)

// Enum value maps for ChatToken_Type.
var (
	ChatToken_Type_name = map[int32]string{
		0: "GENERATION_START",
		1: "TOKEN",
		2: "THOUGHT",
		3: "COMPLETE",
		4: "ERROR",
	}
	ChatToken_Type_value = map[string]int32{
		"GENERATION_START": 0,
		"TOKEN":            1,
		"THOUGHT":          2,
		"COMPLETE":         3,
		"ERROR":            4,
	}
)

func (x ChatToken_Type) Enum() *ChatToken_Type {
	p := new(ChatToken_Type)
	*p = x
	return p
}

func (x ChatToken_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatToken_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ai_proto_enumTypes[0].Descriptor()
}

func (ChatToken_Type) Type() protoreflect.EnumType {
	return &file_proto_ai_proto_enumTypes[0]
}

func (x ChatToken_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatToken_Type.Descriptor instead.
func (ChatToken_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{4, 0}
}

type UIToken_Type int32

const (
	UIToken_GENERATION_START UIToken_Type = 0
	UIToken_THOUGHT          UIToken_Type = 1
	UIToken_TOKEN            UIToken_Type = 2
	UIToken_COMPLETE         UIToken_Type = 3
	UIToken_ERROR            UIToken_Type = 4
)

// Enum value maps for UIToken_Type.
var (
	UIToken_Type_name = map[int32]string{
		0: "GENERATION_START",
		1: "THOUGHT",
		2: "TOKEN",
		3: "COMPLETE",
		4: "ERROR",
	}
	UIToken_Type_value = map[string]int32{
		"GENERATION_START": 0,
		"THOUGHT":          1,
		"TOKEN":            2,
		"COMPLETE":         3,
		"ERROR":            4,
	}
)

func (x UIToken_Type) Enum() *UIToken_Type {
	p := new(UIToken_Type)
	*p = x
	return p
}

func (x UIToken_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UIToken_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ai_proto_enumTypes[1].Descriptor()
}

func (UIToken_Type) Type() protoreflect.EnumType {
	return &file_proto_ai_proto_enumTypes[1]
}

func (x UIToken_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UIToken_Type.Descriptor instead.
func (UIToken_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{5, 0}
}

type UIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Context       map[string]string      `protobuf:"bytes,2,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ParentId      *string                `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIRequest) Reset() {
	*x = UIRequest{}
	mi := &file_proto_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIRequest) ProtoMessage() {}

func (x *UIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIRequest.ProtoReflect.Descriptor instead.
func (*UIRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{0}
}

func (x *UIRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UIRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *UIRequest) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

type UIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	UiSpecJson    string                 `protobuf:"bytes,2,opt,name=ui_spec_json,json=uiSpecJson,proto3" json:"ui_spec_json,omitempty"`
	Thoughts      []string               `protobuf:"bytes,3,rep,name=thoughts,proto3" json:"thoughts,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Error         *string                `protobuf:"bytes,5,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIResponse) Reset() {
	*x = UIResponse{}
	mi := &file_proto_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIResponse) ProtoMessage() {}

func (x *UIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIResponse.ProtoReflect.Descriptor instead.
func (*UIResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{1}
}

func (x *UIResponse) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *UIResponse) GetUiSpecJson() string {
	if x != nil {
		return x.UiSpecJson
	}
	return ""
}

func (x *UIResponse) GetThoughts() []string {
	if x != nil {
		return x.Thoughts
	}
	return nil
}

func (x *UIResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UIResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Context       map[string]string      `protobuf:"bytes,2,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	History       []*ChatMessage         `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_proto_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{2}
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ChatRequest) GetHistory() []*ChatMessage {
	if x != nil {
		return x.History
	}
	return nil
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{3}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ChatToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ChatToken_Type         `protobuf:"varint,1,opt,name=type,proto3,enum=ai.ChatToken_Type" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatToken) Reset() {
	*x = ChatToken{}
	mi := &file_proto_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatToken) ProtoMessage() {}

func (x *ChatToken) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatToken.ProtoReflect.Descriptor instead.
func (*ChatToken) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{4}
}

func (x *ChatToken) GetType() ChatToken_Type {
	if x != nil {
		return x.Type
	}
	return ChatToken_GENERATION_START
}

func (x *ChatToken) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatToken) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type UIToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          UIToken_Type           `protobuf:"varint,1,opt,name=type,proto3,enum=ai.UIToken_Type" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIToken) Reset() {
	*x = UIToken{}
	mi := &file_proto_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIToken) ProtoMessage() {}

func (x *UIToken) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIToken.ProtoReflect.Descriptor instead.
func (*UIToken) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{5}
}

func (x *UIToken) GetType() UIToken_Type {
	if x != nil {
		return x.Type
	}
	return UIToken_GENERATION_START
}

func (x *UIToken) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UIToken) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_ai_proto protoreflect.FileDescriptor

const file_proto_ai_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/ai.proto\x12\x02ai\"\xc7\x01\n" +
	"\tUIRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x124\n" +
	"\acontext\x18\x02 \x03(\v2\x1a.ai.UIRequest.ContextEntryR\acontext\x12 \n" +
	"\tparent_id\x18\x03 \x01(\tH\x00R\bparentId\x88\x01\x01\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_parent_id\"\xa0\x01\n" +
	"\n" +
	"UIResponse\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12 \n" +
	"\fui_spec_json\x18\x02 \x01(\tR\n" +
	"uiSpecJson\x12\x1a\n" +
	"\bthoughts\x18\x03 \x03(\tR\bthoughts\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x19\n" +
	"\x05error\x18\x05 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xc6\x01\n" +
	"\vChatRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x126\n" +
	"\acontext\x18\x02 \x03(\v2\x1c.ai.ChatRequest.ContextEntryR\acontext\x12)\n" +
	"\ahistory\x18\x03 \x03(\v2\x0f.ai.ChatMessageR\ahistory\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Y\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\xba\x01\n" +
	"\tChatToken\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.ai.ChatToken.TypeR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"M\n" +
	"\x04Type\x12\x14\n" +
	"\x10GENERATION_START\x10\x00\x12\t\n" +
	"\x05TOKEN\x10\x01\x12\v\n" +
	"\aTHOUGHT\x10\x02\x12\f\n" +
	"\bCOMPLETE\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04\"\xb6\x01\n" +
	"\aUIToken\x12$\n" +
	"\x04type\x18\x01 \x01(\x0e2\x10.ai.UIToken.TypeR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"M\n" +
	"\x04Type\x12\x14\n" +
	"\x10GENERATION_START\x10\x00\x12\v\n" +
	"\aTHOUGHT\x10\x01\x12\t\n" +
	"\x05TOKEN\x10\x02\x12\f\n" +
	"\bCOMPLETE\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x042\x92\x01\n" +
	"\tAIService\x12+\n" +
	"\n" +
	"GenerateUI\x12\r.ai.UIRequest\x1a\x0e.ai.UIResponse\x12.\n" +
	"\n" +
	"StreamChat\x12\x0f.ai.ChatRequest\x1a\r.ai.ChatToken0\x01\x12(\n" +
	"\bStreamUI\x12\r.ai.UIRequest\x1a\v.ai.UIToken0\x01B4Z2github.com/GriffinCanCode/AgentOS/backend/proto/aib\x06proto3"

var (
	file_proto_ai_proto_rawDescOnce sync.Once
	file_proto_ai_proto_rawDescData []byte
)

func file_proto_ai_proto_rawDescGZIP() []byte {
	file_proto_ai_proto_rawDescOnce.Do(func() {
		file_proto_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ai_proto_rawDesc), len(file_proto_ai_proto_rawDesc)))
	})
	return file_proto_ai_proto_rawDescData
}

var file_proto_ai_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_ai_proto_goTypes = []any{
	(ChatToken_Type)(0), // 0: ai.ChatToken.Type
	(UIToken_Type)(0),   // 1: ai.UIToken.Type
	(*UIRequest)(nil),   // 2: ai.UIRequest
	(*UIResponse)(nil),  // 3: ai.UIResponse
	(*ChatRequest)(nil), // 4: ai.ChatRequest
	(*ChatMessage)(nil), // 5: ai.ChatMessage
	(*ChatToken)(nil),   // 6: ai.ChatToken
	(*UIToken)(nil),     // 7: ai.UIToken
	nil,                 // 8: ai.UIRequest.ContextEntry
	nil,                 // 9: ai.ChatRequest.ContextEntry
}
var file_proto_ai_proto_depIdxs = []int32{
	8, // 0: ai.UIRequest.context:type_name -> ai.UIRequest.ContextEntry
	9, // 1: ai.ChatRequest.context:type_name -> ai.ChatRequest.ContextEntry
	5, // 2: ai.ChatRequest.history:type_name -> ai.ChatMessage
	0, // 3: ai.ChatToken.type:type_name -> ai.ChatToken.Type
	1, // 4: ai.UIToken.type:type_name -> ai.UIToken.Type
	2, // 5: ai.AIService.GenerateUI:input_type -> ai.UIRequest
	4, // 6: ai.AIService.StreamChat:input_type -> ai.ChatRequest
	2, // 7: ai.AIService.StreamUI:input_type -> ai.UIRequest
	3, // 8: ai.AIService.GenerateUI:output_type -> ai.UIResponse
	6, // 9: ai.AIService.StreamChat:output_type -> ai.ChatToken
	7, // 10: ai.AIService.StreamUI:output_type -> ai.UIToken
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_ai_proto_init() }
func file_proto_ai_proto_init() {
	if File_proto_ai_proto != nil {
		return
	}
	file_proto_ai_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_ai_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ai_proto_rawDesc), len(file_proto_ai_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ai_proto_goTypes,
		DependencyIndexes: file_proto_ai_proto_depIdxs,
		EnumInfos:         file_proto_ai_proto_enumTypes,
		MessageInfos:      file_proto_ai_proto_msgTypes,
	}.Build()
	File_proto_ai_proto = out.File
	file_proto_ai_proto_goTypes = nil
	file_proto_ai_proto_depIdxs = nil
}
