// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: ai.proto

package ai

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIService_GenerateUI_FullMethodName = "/ai.AIService/GenerateUI"
	AIService_StreamChat_FullMethodName = "/ai.AIService/StreamChat"
	AIService_StreamUI_FullMethodName   = "/ai.AIService/StreamUI"
)

// AIServiceClient is the client API for AIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AI service for LLM operations
type AIServiceClient interface {
	// Generate UI specification from natural language
	GenerateUI(ctx context.Context, in *UIRequest, opts ...grpc.CallOption) (*UIResponse, error)
	// Stream chat response with thoughts
	StreamChat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatToken], error)
	// Stream UI generation with real-time updates
	StreamUI(ctx context.Context, in *UIRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UIToken], error)
}

type aIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIServiceClient(cc grpc.ClientConnInterface) AIServiceClient {
	return &aIServiceClient{cc}
}

func (c *aIServiceClient) GenerateUI(ctx context.Context, in *UIRequest, opts ...grpc.CallOption) (*UIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UIResponse)
	err := c.cc.Invoke(ctx, AIService_GenerateUI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) StreamChat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatToken], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AIService_ServiceDesc.Streams[0], AIService_StreamChat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatToken]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIService_StreamChatClient = grpc.ServerStreamingClient[ChatToken]

func (c *aIServiceClient) StreamUI(ctx context.Context, in *UIRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UIToken], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AIService_ServiceDesc.Streams[1], AIService_StreamUI_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UIRequest, UIToken]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIService_StreamUIClient = grpc.ServerStreamingClient[UIToken]

// AIServiceServer is the server API for AIService service.
// All implementations must embed UnimplementedAIServiceServer
// for forward compatibility.
//
// AI service for LLM operations
type AIServiceServer interface {
	// Generate UI specification from natural language
	GenerateUI(context.Context, *UIRequest) (*UIResponse, error)
	// Stream chat response with thoughts
	StreamChat(*ChatRequest, grpc.ServerStreamingServer[ChatToken]) error
	// Stream UI generation with real-time updates
	StreamUI(*UIRequest, grpc.ServerStreamingServer[UIToken]) error
	mustEmbedUnimplementedAIServiceServer()
}

// UnimplementedAIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIServiceServer struct{}

func (UnimplementedAIServiceServer) GenerateUI(context.Context, *UIRequest) (*UIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateUI not implemented")
}
func (UnimplementedAIServiceServer) StreamChat(*ChatRequest, grpc.ServerStreamingServer[ChatToken]) error {
	return status.Errorf(codes.Unimplemented, "method StreamChat not implemented")
}
func (UnimplementedAIServiceServer) StreamUI(*UIRequest, grpc.ServerStreamingServer[UIToken]) error {
	return status.Errorf(codes.Unimplemented, "method StreamUI not implemented")
}
func (UnimplementedAIServiceServer) mustEmbedUnimplementedAIServiceServer() {}
func (UnimplementedAIServiceServer) testEmbeddedByValue()                   {}

// UnsafeAIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIServiceServer will
// result in compilation errors.
type UnsafeAIServiceServer interface {
	mustEmbedUnimplementedAIServiceServer()
}

func RegisterAIServiceServer(s grpc.ServiceRegistrar, srv AIServiceServer) {
	// If the following call pancis, it indicates UnimplementedAIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIService_ServiceDesc, srv)
}

func _AIService_GenerateUI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).GenerateUI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_GenerateUI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).GenerateUI(ctx, req.(*UIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_StreamChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIServiceServer).StreamChat(m, &grpc.GenericServerStream[ChatRequest, ChatToken]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIService_StreamChatServer = grpc.ServerStreamingServer[ChatToken]

func _AIService_StreamUI_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UIRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIServiceServer).StreamUI(m, &grpc.GenericServerStream[UIRequest, UIToken]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIService_StreamUIServer = grpc.ServerStreamingServer[UIToken]

// AIService_ServiceDesc is the grpc.ServiceDesc for AIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.AIService",
	HandlerType: (*AIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateUI",
			Handler:    _AIService_GenerateUI_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamChat",
			Handler:       _AIService_StreamChat_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamUI",
			Handler:       _AIService_StreamUI_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ai.proto",
}
