// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: kernel.proto

package kernel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SandboxLevel int32

const (
	SandboxLevel_MINIMAL    SandboxLevel = 0
	SandboxLevel_STANDARD   SandboxLevel = 1
	SandboxLevel_PRIVILEGED SandboxLevel = 2
)

// Enum value maps for SandboxLevel.
var (
	SandboxLevel_name = map[int32]string{
		0: "MINIMAL",
		1: "STANDARD",
		2: "PRIVILEGED",
	}
	SandboxLevel_value = map[string]int32{
		"MINIMAL":    0,
		"STANDARD":   1,
		"PRIVILEGED": 2,
	}
)

func (x SandboxLevel) Enum() *SandboxLevel {
	p := new(SandboxLevel)
	*p = x
	return p
}

func (x SandboxLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SandboxLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_kernel_proto_enumTypes[0].Descriptor()
}

func (SandboxLevel) Type() protoreflect.EnumType {
	return &file_kernel_proto_enumTypes[0]
}

func (x SandboxLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SandboxLevel.Descriptor instead.
func (SandboxLevel) EnumDescriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{0}
}

type Capability int32

const (
	Capability_READ_FILE       Capability = 0
	Capability_WRITE_FILE      Capability = 1
	Capability_CREATE_FILE     Capability = 2
	Capability_DELETE_FILE     Capability = 3
	Capability_LIST_DIRECTORY  Capability = 4
	Capability_SPAWN_PROCESS   Capability = 5
	Capability_KILL_PROCESS    Capability = 6
	Capability_NETWORK_ACCESS  Capability = 7
	Capability_BIND_PORT       Capability = 8
	Capability_SYSTEM_INFO     Capability = 9
	Capability_TIME_ACCESS     Capability = 10
	Capability_SEND_MESSAGE    Capability = 11
	Capability_RECEIVE_MESSAGE Capability = 12
)

// Enum value maps for Capability.
var (
	Capability_name = map[int32]string{
		0:  "READ_FILE",
		1:  "WRITE_FILE",
		2:  "CREATE_FILE",
		3:  "DELETE_FILE",
		4:  "LIST_DIRECTORY",
		5:  "SPAWN_PROCESS",
		6:  "KILL_PROCESS",
		7:  "NETWORK_ACCESS",
		8:  "BIND_PORT",
		9:  "SYSTEM_INFO",
		10: "TIME_ACCESS",
		11: "SEND_MESSAGE",
		12: "RECEIVE_MESSAGE",
	}
	Capability_value = map[string]int32{
		"READ_FILE":       0,
		"WRITE_FILE":      1,
		"CREATE_FILE":     2,
		"DELETE_FILE":     3,
		"LIST_DIRECTORY":  4,
		"SPAWN_PROCESS":   5,
		"KILL_PROCESS":    6,
		"NETWORK_ACCESS":  7,
		"BIND_PORT":       8,
		"SYSTEM_INFO":     9,
		"TIME_ACCESS":     10,
		"SEND_MESSAGE":    11,
		"RECEIVE_MESSAGE": 12,
	}
)

func (x Capability) Enum() *Capability {
	p := new(Capability)
	*p = x
	return p
}

func (x Capability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Capability) Descriptor() protoreflect.EnumDescriptor {
	return file_kernel_proto_enumTypes[1].Descriptor()
}

func (Capability) Type() protoreflect.EnumType {
	return &file_kernel_proto_enumTypes[1]
}

func (x Capability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Capability.Descriptor instead.
func (Capability) EnumDescriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{1}
}

type SyscallRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Pid   uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	// Types that are valid to be assigned to Syscall:
	//
	//	*SyscallRequest_ReadFile
	//	*SyscallRequest_WriteFile
	//	*SyscallRequest_CreateFile
	//	*SyscallRequest_DeleteFile
	//	*SyscallRequest_ListDirectory
	//	*SyscallRequest_FileExists
	//	*SyscallRequest_FileStat
	//	*SyscallRequest_MoveFile
	//	*SyscallRequest_CopyFile
	//	*SyscallRequest_CreateDirectory
	//	*SyscallRequest_SpawnProcess
	//	*SyscallRequest_KillProcess
	//	*SyscallRequest_GetSystemInfo
	//	*SyscallRequest_GetCurrentTime
	//	*SyscallRequest_GetEnvVar
	//	*SyscallRequest_NetworkRequest
	Syscall       isSyscallRequest_Syscall `protobuf_oneof:"syscall"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyscallRequest) Reset() {
	*x = SyscallRequest{}
	mi := &file_kernel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyscallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyscallRequest) ProtoMessage() {}

func (x *SyscallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyscallRequest.ProtoReflect.Descriptor instead.
func (*SyscallRequest) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{0}
}

func (x *SyscallRequest) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SyscallRequest) GetSyscall() isSyscallRequest_Syscall {
	if x != nil {
		return x.Syscall
	}
	return nil
}

func (x *SyscallRequest) GetReadFile() *ReadFileCall {
	if x != nil {
		if x, ok := x.Syscall.(*SyscallRequest_ReadFile); ok {
			return x.ReadFile
		}
	}
	return nil
}

func (x *SyscallRequest) GetWriteFile() *WriteFileCall {
	if x != nil {
		if x, ok := x.Syscall.(*SyscallRequest_WriteFile); ok {
			return x.WriteFile
		}
	}
	return nil
}

func (x *SyscallRequest) GetCreateFile() *CreateFileCall {
	if x != nil {
		if x, ok := x.Syscall.(*SyscallRequest_CreateFile); ok {
			return x.CreateFile
		}
	}
	return nil
}

func (x *SyscallRequest) GetDeleteFile() *DeleteFileCall {
	if x != nil {
		if x, ok := x.Syscall.(*SyscallRequest_DeleteFile); ok {
			return x.DeleteFile
		}
	}
	return nil
}

func (x *SyscallRequest) GetListDirectory() *ListDirectoryCall {
	if x != nil {
		if x, ok := x.Syscall.(*SyscallRequest_ListDirectory); ok {
			return x.ListDirectory
		}
	}
	return nil
}

func (x *SyscallRequest) GetFileExists() *FileExistsCall {
	if x != nil {
		if x, ok := x.Syscall.(*SyscallRequest_FileExists); ok {
			return x.FileExists
		}
	}
	return nil
}

func (x *SyscallRequest) GetFileStat() *FileStatCall {
	if x != nil {
		if x, ok := x.Syscall.(*SyscallRequest_FileStat); ok {
			return x.FileStat
		}
	}
	return nil
}

func (x *SyscallRequest) GetMoveFile() *MoveFileCall {
	if x != nil {
		if x, ok := x.Syscall.(*SyscallRequest_MoveFile); ok {
			return x.MoveFile
		}
	}
	return nil
}

func (x *SyscallRequest) GetCopyFile() *CopyFileCall {
	if x != nil {
		if x, ok := x.Syscall.(*SyscallRequest_CopyFile); ok {
			return x.CopyFile
		}
	}
	return nil
}

func (x *SyscallRequest) GetCreateDirectory() *CreateDirectoryCall {
	if x != nil {
		if x, ok := x.Syscall.(*SyscallRequest_CreateDirectory); ok {
			return x.CreateDirectory
		}
	}
	return nil
}

func (x *SyscallRequest) GetSpawnProcess() *SpawnProcessCall {
	if x != nil {
		if x, ok := x.Syscall.(*SyscallRequest_SpawnProcess); ok {
			return x.SpawnProcess
		}
	}
	return nil
}

func (x *SyscallRequest) GetKillProcess() *KillProcessCall {
	if x != nil {
		if x, ok := x.Syscall.(*SyscallRequest_KillProcess); ok {
			return x.KillProcess
		}
	}
	return nil
}

func (x *SyscallRequest) GetGetSystemInfo() *GetSystemInfoCall {
	if x != nil {
		if x, ok := x.Syscall.(*SyscallRequest_GetSystemInfo); ok {
			return x.GetSystemInfo
		}
	}
	return nil
}

func (x *SyscallRequest) GetGetCurrentTime() *GetCurrentTimeCall {
	if x != nil {
		if x, ok := x.Syscall.(*SyscallRequest_GetCurrentTime); ok {
			return x.GetCurrentTime
		}
	}
	return nil
}

func (x *SyscallRequest) GetGetEnvVar() *GetEnvVarCall {
	if x != nil {
		if x, ok := x.Syscall.(*SyscallRequest_GetEnvVar); ok {
			return x.GetEnvVar
		}
	}
	return nil
}

func (x *SyscallRequest) GetNetworkRequest() *NetworkRequestCall {
	if x != nil {
		if x, ok := x.Syscall.(*SyscallRequest_NetworkRequest); ok {
			return x.NetworkRequest
		}
	}
	return nil
}

type isSyscallRequest_Syscall interface {
	isSyscallRequest_Syscall()
}

type SyscallRequest_ReadFile struct {
	ReadFile *ReadFileCall `protobuf:"bytes,10,opt,name=read_file,json=readFile,proto3,oneof"`
}

type SyscallRequest_WriteFile struct {
	WriteFile *WriteFileCall `protobuf:"bytes,11,opt,name=write_file,json=writeFile,proto3,oneof"`
}

type SyscallRequest_CreateFile struct {
	CreateFile *CreateFileCall `protobuf:"bytes,12,opt,name=create_file,json=createFile,proto3,oneof"`
}

type SyscallRequest_DeleteFile struct {
	DeleteFile *DeleteFileCall `protobuf:"bytes,13,opt,name=delete_file,json=deleteFile,proto3,oneof"`
}

type SyscallRequest_ListDirectory struct {
	ListDirectory *ListDirectoryCall `protobuf:"bytes,14,opt,name=list_directory,json=listDirectory,proto3,oneof"`
}

type SyscallRequest_FileExists struct {
	FileExists *FileExistsCall `protobuf:"bytes,15,opt,name=file_exists,json=fileExists,proto3,oneof"`
}

type SyscallRequest_FileStat struct {
	FileStat *FileStatCall `protobuf:"bytes,16,opt,name=file_stat,json=fileStat,proto3,oneof"`
}

type SyscallRequest_MoveFile struct {
	MoveFile *MoveFileCall `protobuf:"bytes,17,opt,name=move_file,json=moveFile,proto3,oneof"`
}

type SyscallRequest_CopyFile struct {
	CopyFile *CopyFileCall `protobuf:"bytes,18,opt,name=copy_file,json=copyFile,proto3,oneof"`
}

type SyscallRequest_CreateDirectory struct {
	CreateDirectory *CreateDirectoryCall `protobuf:"bytes,19,opt,name=create_directory,json=createDirectory,proto3,oneof"`
}

type SyscallRequest_SpawnProcess struct {
	SpawnProcess *SpawnProcessCall `protobuf:"bytes,20,opt,name=spawn_process,json=spawnProcess,proto3,oneof"`
}

type SyscallRequest_KillProcess struct {
	KillProcess *KillProcessCall `protobuf:"bytes,21,opt,name=kill_process,json=killProcess,proto3,oneof"`
}

type SyscallRequest_GetSystemInfo struct {
	GetSystemInfo *GetSystemInfoCall `protobuf:"bytes,30,opt,name=get_system_info,json=getSystemInfo,proto3,oneof"`
}

type SyscallRequest_GetCurrentTime struct {
	GetCurrentTime *GetCurrentTimeCall `protobuf:"bytes,31,opt,name=get_current_time,json=getCurrentTime,proto3,oneof"`
}

type SyscallRequest_GetEnvVar struct {
	GetEnvVar *GetEnvVarCall `protobuf:"bytes,32,opt,name=get_env_var,json=getEnvVar,proto3,oneof"`
}

type SyscallRequest_NetworkRequest struct {
	NetworkRequest *NetworkRequestCall `protobuf:"bytes,40,opt,name=network_request,json=networkRequest,proto3,oneof"`
}

func (*SyscallRequest_ReadFile) isSyscallRequest_Syscall() {}

func (*SyscallRequest_WriteFile) isSyscallRequest_Syscall() {}

func (*SyscallRequest_CreateFile) isSyscallRequest_Syscall() {}

func (*SyscallRequest_DeleteFile) isSyscallRequest_Syscall() {}

func (*SyscallRequest_ListDirectory) isSyscallRequest_Syscall() {}

func (*SyscallRequest_FileExists) isSyscallRequest_Syscall() {}

func (*SyscallRequest_FileStat) isSyscallRequest_Syscall() {}

func (*SyscallRequest_MoveFile) isSyscallRequest_Syscall() {}

func (*SyscallRequest_CopyFile) isSyscallRequest_Syscall() {}

func (*SyscallRequest_CreateDirectory) isSyscallRequest_Syscall() {}

func (*SyscallRequest_SpawnProcess) isSyscallRequest_Syscall() {}

func (*SyscallRequest_KillProcess) isSyscallRequest_Syscall() {}

func (*SyscallRequest_GetSystemInfo) isSyscallRequest_Syscall() {}

func (*SyscallRequest_GetCurrentTime) isSyscallRequest_Syscall() {}

func (*SyscallRequest_GetEnvVar) isSyscallRequest_Syscall() {}

func (*SyscallRequest_NetworkRequest) isSyscallRequest_Syscall() {}

type SyscallResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*SyscallResponse_Success
	//	*SyscallResponse_Error
	//	*SyscallResponse_PermissionDenied
	Result        isSyscallResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyscallResponse) Reset() {
	*x = SyscallResponse{}
	mi := &file_kernel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyscallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyscallResponse) ProtoMessage() {}

func (x *SyscallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyscallResponse.ProtoReflect.Descriptor instead.
func (*SyscallResponse) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{1}
}

func (x *SyscallResponse) GetResult() isSyscallResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *SyscallResponse) GetSuccess() *SuccessResult {
	if x != nil {
		if x, ok := x.Result.(*SyscallResponse_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *SyscallResponse) GetError() *ErrorResult {
	if x != nil {
		if x, ok := x.Result.(*SyscallResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *SyscallResponse) GetPermissionDenied() *PermissionDeniedResult {
	if x != nil {
		if x, ok := x.Result.(*SyscallResponse_PermissionDenied); ok {
			return x.PermissionDenied
		}
	}
	return nil
}

type isSyscallResponse_Result interface {
	isSyscallResponse_Result()
}

type SyscallResponse_Success struct {
	Success *SuccessResult `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type SyscallResponse_Error struct {
	Error *ErrorResult `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type SyscallResponse_PermissionDenied struct {
	PermissionDenied *PermissionDeniedResult `protobuf:"bytes,3,opt,name=permission_denied,json=permissionDenied,proto3,oneof"`
}

func (*SyscallResponse_Success) isSyscallResponse_Result() {}

func (*SyscallResponse_Error) isSyscallResponse_Result() {}

func (*SyscallResponse_PermissionDenied) isSyscallResponse_Result() {}

type SuccessResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessResult) Reset() {
	*x = SuccessResult{}
	mi := &file_kernel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessResult) ProtoMessage() {}

func (x *SuccessResult) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessResult.ProtoReflect.Descriptor instead.
func (*SuccessResult) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{2}
}

func (x *SuccessResult) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ErrorResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResult) Reset() {
	*x = ErrorResult{}
	mi := &file_kernel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResult) ProtoMessage() {}

func (x *ErrorResult) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResult.ProtoReflect.Descriptor instead.
func (*ErrorResult) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PermissionDeniedResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionDeniedResult) Reset() {
	*x = PermissionDeniedResult{}
	mi := &file_kernel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionDeniedResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionDeniedResult) ProtoMessage() {}

func (x *PermissionDeniedResult) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionDeniedResult.ProtoReflect.Descriptor instead.
func (*PermissionDeniedResult) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{4}
}

func (x *PermissionDeniedResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReadFileCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileCall) Reset() {
	*x = ReadFileCall{}
	mi := &file_kernel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileCall) ProtoMessage() {}

func (x *ReadFileCall) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileCall.ProtoReflect.Descriptor instead.
func (*ReadFileCall) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{5}
}

func (x *ReadFileCall) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type WriteFileCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileCall) Reset() {
	*x = WriteFileCall{}
	mi := &file_kernel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileCall) ProtoMessage() {}

func (x *WriteFileCall) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileCall.ProtoReflect.Descriptor instead.
func (*WriteFileCall) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{6}
}

func (x *WriteFileCall) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileCall) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateFileCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileCall) Reset() {
	*x = CreateFileCall{}
	mi := &file_kernel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileCall) ProtoMessage() {}

func (x *CreateFileCall) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileCall.ProtoReflect.Descriptor instead.
func (*CreateFileCall) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{7}
}

func (x *CreateFileCall) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DeleteFileCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileCall) Reset() {
	*x = DeleteFileCall{}
	mi := &file_kernel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileCall) ProtoMessage() {}

func (x *DeleteFileCall) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileCall.ProtoReflect.Descriptor instead.
func (*DeleteFileCall) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteFileCall) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListDirectoryCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirectoryCall) Reset() {
	*x = ListDirectoryCall{}
	mi := &file_kernel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirectoryCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectoryCall) ProtoMessage() {}

func (x *ListDirectoryCall) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectoryCall.ProtoReflect.Descriptor instead.
func (*ListDirectoryCall) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{9}
}

func (x *ListDirectoryCall) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileExistsCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileExistsCall) Reset() {
	*x = FileExistsCall{}
	mi := &file_kernel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileExistsCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileExistsCall) ProtoMessage() {}

func (x *FileExistsCall) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileExistsCall.ProtoReflect.Descriptor instead.
func (*FileExistsCall) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{10}
}

func (x *FileExistsCall) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileStatCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileStatCall) Reset() {
	*x = FileStatCall{}
	mi := &file_kernel_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileStatCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStatCall) ProtoMessage() {}

func (x *FileStatCall) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStatCall.ProtoReflect.Descriptor instead.
func (*FileStatCall) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{11}
}

func (x *FileStatCall) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type MoveFileCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveFileCall) Reset() {
	*x = MoveFileCall{}
	mi := &file_kernel_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveFileCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveFileCall) ProtoMessage() {}

func (x *MoveFileCall) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveFileCall.ProtoReflect.Descriptor instead.
func (*MoveFileCall) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{12}
}

func (x *MoveFileCall) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *MoveFileCall) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type CopyFileCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyFileCall) Reset() {
	*x = CopyFileCall{}
	mi := &file_kernel_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyFileCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyFileCall) ProtoMessage() {}

func (x *CopyFileCall) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyFileCall.ProtoReflect.Descriptor instead.
func (*CopyFileCall) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{13}
}

func (x *CopyFileCall) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CopyFileCall) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type CreateDirectoryCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectoryCall) Reset() {
	*x = CreateDirectoryCall{}
	mi := &file_kernel_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectoryCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectoryCall) ProtoMessage() {}

func (x *CreateDirectoryCall) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectoryCall.ProtoReflect.Descriptor instead.
func (*CreateDirectoryCall) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{14}
}

func (x *CreateDirectoryCall) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SpawnProcessCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnProcessCall) Reset() {
	*x = SpawnProcessCall{}
	mi := &file_kernel_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnProcessCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnProcessCall) ProtoMessage() {}

func (x *SpawnProcessCall) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnProcessCall.ProtoReflect.Descriptor instead.
func (*SpawnProcessCall) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{15}
}

func (x *SpawnProcessCall) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *SpawnProcessCall) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type KillProcessCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetPid     uint32                 `protobuf:"varint,1,opt,name=target_pid,json=targetPid,proto3" json:"target_pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillProcessCall) Reset() {
	*x = KillProcessCall{}
	mi := &file_kernel_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillProcessCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillProcessCall) ProtoMessage() {}

func (x *KillProcessCall) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillProcessCall.ProtoReflect.Descriptor instead.
func (*KillProcessCall) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{16}
}

func (x *KillProcessCall) GetTargetPid() uint32 {
	if x != nil {
		return x.TargetPid
	}
	return 0
}

type GetSystemInfoCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemInfoCall) Reset() {
	*x = GetSystemInfoCall{}
	mi := &file_kernel_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemInfoCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoCall) ProtoMessage() {}

func (x *GetSystemInfoCall) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoCall.ProtoReflect.Descriptor instead.
func (*GetSystemInfoCall) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{17}
}

type GetCurrentTimeCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentTimeCall) Reset() {
	*x = GetCurrentTimeCall{}
	mi := &file_kernel_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentTimeCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentTimeCall) ProtoMessage() {}

func (x *GetCurrentTimeCall) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentTimeCall.ProtoReflect.Descriptor instead.
func (*GetCurrentTimeCall) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{18}
}

type GetEnvVarCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvVarCall) Reset() {
	*x = GetEnvVarCall{}
	mi := &file_kernel_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvVarCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvVarCall) ProtoMessage() {}

func (x *GetEnvVarCall) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvVarCall.ProtoReflect.Descriptor instead.
func (*GetEnvVarCall) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{19}
}

func (x *GetEnvVarCall) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type NetworkRequestCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkRequestCall) Reset() {
	*x = NetworkRequestCall{}
	mi := &file_kernel_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkRequestCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkRequestCall) ProtoMessage() {}

func (x *NetworkRequestCall) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkRequestCall.ProtoReflect.Descriptor instead.
func (*NetworkRequestCall) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{20}
}

func (x *NetworkRequestCall) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreateProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Priority      uint32                 `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	SandboxLevel  SandboxLevel           `protobuf:"varint,3,opt,name=sandbox_level,json=sandboxLevel,proto3,enum=kernel.SandboxLevel" json:"sandbox_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProcessRequest) Reset() {
	*x = CreateProcessRequest{}
	mi := &file_kernel_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProcessRequest) ProtoMessage() {}

func (x *CreateProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProcessRequest.ProtoReflect.Descriptor instead.
func (*CreateProcessRequest) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{21}
}

func (x *CreateProcessRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProcessRequest) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CreateProcessRequest) GetSandboxLevel() SandboxLevel {
	if x != nil {
		return x.SandboxLevel
	}
	return SandboxLevel_MINIMAL
}

type CreateProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProcessResponse) Reset() {
	*x = CreateProcessResponse{}
	mi := &file_kernel_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProcessResponse) ProtoMessage() {}

func (x *CreateProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProcessResponse.ProtoReflect.Descriptor instead.
func (*CreateProcessResponse) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{22}
}

func (x *CreateProcessResponse) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *CreateProcessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateProcessResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Capabilities  []Capability           `protobuf:"varint,2,rep,packed,name=capabilities,proto3,enum=kernel.Capability" json:"capabilities,omitempty"`
	AllowedPaths  []string               `protobuf:"bytes,3,rep,name=allowed_paths,json=allowedPaths,proto3" json:"allowed_paths,omitempty"`
	BlockedPaths  []string               `protobuf:"bytes,4,rep,name=blocked_paths,json=blockedPaths,proto3" json:"blocked_paths,omitempty"`
	Limits        *ResourceLimits        `protobuf:"bytes,5,opt,name=limits,proto3" json:"limits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSandboxRequest) Reset() {
	*x = UpdateSandboxRequest{}
	mi := &file_kernel_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSandboxRequest) ProtoMessage() {}

func (x *UpdateSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSandboxRequest.ProtoReflect.Descriptor instead.
func (*UpdateSandboxRequest) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateSandboxRequest) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *UpdateSandboxRequest) GetCapabilities() []Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *UpdateSandboxRequest) GetAllowedPaths() []string {
	if x != nil {
		return x.AllowedPaths
	}
	return nil
}

func (x *UpdateSandboxRequest) GetBlockedPaths() []string {
	if x != nil {
		return x.BlockedPaths
	}
	return nil
}

func (x *UpdateSandboxRequest) GetLimits() *ResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

type UpdateSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSandboxResponse) Reset() {
	*x = UpdateSandboxResponse{}
	mi := &file_kernel_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSandboxResponse) ProtoMessage() {}

func (x *UpdateSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSandboxResponse.ProtoReflect.Descriptor instead.
func (*UpdateSandboxResponse) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateSandboxResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateSandboxResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ResourceLimits struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MaxMemoryBytes        uint64                 `protobuf:"varint,1,opt,name=max_memory_bytes,json=maxMemoryBytes,proto3" json:"max_memory_bytes,omitempty"`
	MaxCpuTimeMs          uint64                 `protobuf:"varint,2,opt,name=max_cpu_time_ms,json=maxCpuTimeMs,proto3" json:"max_cpu_time_ms,omitempty"`
	MaxFileDescriptors    uint32                 `protobuf:"varint,3,opt,name=max_file_descriptors,json=maxFileDescriptors,proto3" json:"max_file_descriptors,omitempty"`
	MaxProcesses          uint32                 `protobuf:"varint,4,opt,name=max_processes,json=maxProcesses,proto3" json:"max_processes,omitempty"`
	MaxNetworkConnections uint32                 `protobuf:"varint,5,opt,name=max_network_connections,json=maxNetworkConnections,proto3" json:"max_network_connections,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_kernel_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{25}
}

func (x *ResourceLimits) GetMaxMemoryBytes() uint64 {
	if x != nil {
		return x.MaxMemoryBytes
	}
	return 0
}

func (x *ResourceLimits) GetMaxCpuTimeMs() uint64 {
	if x != nil {
		return x.MaxCpuTimeMs
	}
	return 0
}

func (x *ResourceLimits) GetMaxFileDescriptors() uint32 {
	if x != nil {
		return x.MaxFileDescriptors
	}
	return 0
}

func (x *ResourceLimits) GetMaxProcesses() uint32 {
	if x != nil {
		return x.MaxProcesses
	}
	return 0
}

func (x *ResourceLimits) GetMaxNetworkConnections() uint32 {
	if x != nil {
		return x.MaxNetworkConnections
	}
	return 0
}

type EventStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventTypes    []string               `protobuf:"bytes,1,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventStreamRequest) Reset() {
	*x = EventStreamRequest{}
	mi := &file_kernel_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStreamRequest) ProtoMessage() {}

func (x *EventStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStreamRequest.ProtoReflect.Descriptor instead.
func (*EventStreamRequest) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{26}
}

func (x *EventStreamRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type KernelEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*KernelEvent_ProcessCreated
	//	*KernelEvent_ProcessTerminated
	//	*KernelEvent_SyscallExecuted
	//	*KernelEvent_PermissionDenied
	Event         isKernelEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KernelEvent) Reset() {
	*x = KernelEvent{}
	mi := &file_kernel_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelEvent) ProtoMessage() {}

func (x *KernelEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelEvent.ProtoReflect.Descriptor instead.
func (*KernelEvent) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{27}
}

func (x *KernelEvent) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *KernelEvent) GetEvent() isKernelEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *KernelEvent) GetProcessCreated() *ProcessCreatedEvent {
	if x != nil {
		if x, ok := x.Event.(*KernelEvent_ProcessCreated); ok {
			return x.ProcessCreated
		}
	}
	return nil
}

func (x *KernelEvent) GetProcessTerminated() *ProcessTerminatedEvent {
	if x != nil {
		if x, ok := x.Event.(*KernelEvent_ProcessTerminated); ok {
			return x.ProcessTerminated
		}
	}
	return nil
}

func (x *KernelEvent) GetSyscallExecuted() *SyscallExecutedEvent {
	if x != nil {
		if x, ok := x.Event.(*KernelEvent_SyscallExecuted); ok {
			return x.SyscallExecuted
		}
	}
	return nil
}

func (x *KernelEvent) GetPermissionDenied() *PermissionDeniedEvent {
	if x != nil {
		if x, ok := x.Event.(*KernelEvent_PermissionDenied); ok {
			return x.PermissionDenied
		}
	}
	return nil
}

type isKernelEvent_Event interface {
	isKernelEvent_Event()
}

type KernelEvent_ProcessCreated struct {
	ProcessCreated *ProcessCreatedEvent `protobuf:"bytes,10,opt,name=process_created,json=processCreated,proto3,oneof"`
}

type KernelEvent_ProcessTerminated struct {
	ProcessTerminated *ProcessTerminatedEvent `protobuf:"bytes,11,opt,name=process_terminated,json=processTerminated,proto3,oneof"`
}

type KernelEvent_SyscallExecuted struct {
	SyscallExecuted *SyscallExecutedEvent `protobuf:"bytes,12,opt,name=syscall_executed,json=syscallExecuted,proto3,oneof"`
}

type KernelEvent_PermissionDenied struct {
	PermissionDenied *PermissionDeniedEvent `protobuf:"bytes,13,opt,name=permission_denied,json=permissionDenied,proto3,oneof"`
}

func (*KernelEvent_ProcessCreated) isKernelEvent_Event() {}

func (*KernelEvent_ProcessTerminated) isKernelEvent_Event() {}

func (*KernelEvent_SyscallExecuted) isKernelEvent_Event() {}

func (*KernelEvent_PermissionDenied) isKernelEvent_Event() {}

type ProcessCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessCreatedEvent) Reset() {
	*x = ProcessCreatedEvent{}
	mi := &file_kernel_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessCreatedEvent) ProtoMessage() {}

func (x *ProcessCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessCreatedEvent.ProtoReflect.Descriptor instead.
func (*ProcessCreatedEvent) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{28}
}

func (x *ProcessCreatedEvent) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessCreatedEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProcessTerminatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessTerminatedEvent) Reset() {
	*x = ProcessTerminatedEvent{}
	mi := &file_kernel_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessTerminatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessTerminatedEvent) ProtoMessage() {}

func (x *ProcessTerminatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessTerminatedEvent.ProtoReflect.Descriptor instead.
func (*ProcessTerminatedEvent) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{29}
}

func (x *ProcessTerminatedEvent) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessTerminatedEvent) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type SyscallExecutedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	SyscallType   string                 `protobuf:"bytes,2,opt,name=syscall_type,json=syscallType,proto3" json:"syscall_type,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyscallExecutedEvent) Reset() {
	*x = SyscallExecutedEvent{}
	mi := &file_kernel_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyscallExecutedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyscallExecutedEvent) ProtoMessage() {}

func (x *SyscallExecutedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyscallExecutedEvent.ProtoReflect.Descriptor instead.
func (*SyscallExecutedEvent) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{30}
}

func (x *SyscallExecutedEvent) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SyscallExecutedEvent) GetSyscallType() string {
	if x != nil {
		return x.SyscallType
	}
	return ""
}

func (x *SyscallExecutedEvent) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PermissionDeniedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	SyscallType   string                 `protobuf:"bytes,2,opt,name=syscall_type,json=syscallType,proto3" json:"syscall_type,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionDeniedEvent) Reset() {
	*x = PermissionDeniedEvent{}
	mi := &file_kernel_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionDeniedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionDeniedEvent) ProtoMessage() {}

func (x *PermissionDeniedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kernel_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionDeniedEvent.ProtoReflect.Descriptor instead.
func (*PermissionDeniedEvent) Descriptor() ([]byte, []int) {
	return file_kernel_proto_rawDescGZIP(), []int{31}
}

func (x *PermissionDeniedEvent) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *PermissionDeniedEvent) GetSyscallType() string {
	if x != nil {
		return x.SyscallType
	}
	return ""
}

func (x *PermissionDeniedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_kernel_proto protoreflect.FileDescriptor

const file_kernel_proto_rawDesc = "" +
	"\n" +
	"\fkernel.proto\x12\x06kernel\"\x84\b\n" +
	"\x0eSyscallRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x123\n" +
	"\tread_file\x18\n" +
	" \x01(\v2\x14.kernel.ReadFileCallH\x00R\breadFile\x126\n" +
	"\n" +
	"write_file\x18\v \x01(\v2\x15.kernel.WriteFileCallH\x00R\twriteFile\x129\n" +
	"\vcreate_file\x18\f \x01(\v2\x16.kernel.CreateFileCallH\x00R\n" +
	"createFile\x129\n" +
	"\vdelete_file\x18\r \x01(\v2\x16.kernel.DeleteFileCallH\x00R\n" +
	"deleteFile\x12B\n" +
	"\x0elist_directory\x18\x0e \x01(\v2\x19.kernel.ListDirectoryCallH\x00R\rlistDirectory\x129\n" +
	"\vfile_exists\x18\x0f \x01(\v2\x16.kernel.FileExistsCallH\x00R\n" +
	"fileExists\x123\n" +
	"\tfile_stat\x18\x10 \x01(\v2\x14.kernel.FileStatCallH\x00R\bfileStat\x123\n" +
	"\tmove_file\x18\x11 \x01(\v2\x14.kernel.MoveFileCallH\x00R\bmoveFile\x123\n" +
	"\tcopy_file\x18\x12 \x01(\v2\x14.kernel.CopyFileCallH\x00R\bcopyFile\x12H\n" +
	"\x10create_directory\x18\x13 \x01(\v2\x1b.kernel.CreateDirectoryCallH\x00R\x0fcreateDirectory\x12?\n" +
	"\rspawn_process\x18\x14 \x01(\v2\x18.kernel.SpawnProcessCallH\x00R\fspawnProcess\x12<\n" +
	"\fkill_process\x18\x15 \x01(\v2\x17.kernel.KillProcessCallH\x00R\vkillProcess\x12C\n" +
	"\x0fget_system_info\x18\x1e \x01(\v2\x19.kernel.GetSystemInfoCallH\x00R\rgetSystemInfo\x12F\n" +
	"\x10get_current_time\x18\x1f \x01(\v2\x1a.kernel.GetCurrentTimeCallH\x00R\x0egetCurrentTime\x127\n" +
	"\vget_env_var\x18  \x01(\v2\x15.kernel.GetEnvVarCallH\x00R\tgetEnvVar\x12E\n" +
	"\x0fnetwork_request\x18( \x01(\v2\x1a.kernel.NetworkRequestCallH\x00R\x0enetworkRequestB\t\n" +
	"\asyscall\"\xca\x01\n" +
	"\x0fSyscallResponse\x121\n" +
	"\asuccess\x18\x01 \x01(\v2\x15.kernel.SuccessResultH\x00R\asuccess\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x13.kernel.ErrorResultH\x00R\x05error\x12M\n" +
	"\x11permission_denied\x18\x03 \x01(\v2\x1e.kernel.PermissionDeniedResultH\x00R\x10permissionDeniedB\b\n" +
	"\x06result\"#\n" +
	"\rSuccessResult\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"'\n" +
	"\vErrorResult\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"0\n" +
	"\x16PermissionDeniedResult\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\"\n" +
	"\fReadFileCall\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"7\n" +
	"\rWriteFileCall\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"$\n" +
	"\x0eCreateFileCall\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"$\n" +
	"\x0eDeleteFileCall\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"'\n" +
	"\x11ListDirectoryCall\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"$\n" +
	"\x0eFileExistsCall\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\"\n" +
	"\fFileStatCall\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"H\n" +
	"\fMoveFileCall\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\"H\n" +
	"\fCopyFileCall\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\")\n" +
	"\x13CreateDirectoryCall\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"@\n" +
	"\x10SpawnProcessCall\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\"0\n" +
	"\x0fKillProcessCall\x12\x1d\n" +
	"\n" +
	"target_pid\x18\x01 \x01(\rR\ttargetPid\"\x13\n" +
	"\x11GetSystemInfoCall\"\x14\n" +
	"\x12GetCurrentTimeCall\"!\n" +
	"\rGetEnvVarCall\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"&\n" +
	"\x12NetworkRequestCall\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x81\x01\n" +
	"\x14CreateProcessRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\rR\bpriority\x129\n" +
	"\rsandbox_level\x18\x03 \x01(\x0e2\x14.kernel.SandboxLevelR\fsandboxLevel\"Y\n" +
	"\x15CreateProcessResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xda\x01\n" +
	"\x14UpdateSandboxRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x126\n" +
	"\fcapabilities\x18\x02 \x03(\x0e2\x12.kernel.CapabilityR\fcapabilities\x12#\n" +
	"\rallowed_paths\x18\x03 \x03(\tR\fallowedPaths\x12#\n" +
	"\rblocked_paths\x18\x04 \x03(\tR\fblockedPaths\x12.\n" +
	"\x06limits\x18\x05 \x01(\v2\x16.kernel.ResourceLimitsR\x06limits\"G\n" +
	"\x15UpdateSandboxResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xf0\x01\n" +
	"\x0eResourceLimits\x12(\n" +
	"\x10max_memory_bytes\x18\x01 \x01(\x04R\x0emaxMemoryBytes\x12%\n" +
	"\x0fmax_cpu_time_ms\x18\x02 \x01(\x04R\fmaxCpuTimeMs\x120\n" +
	"\x14max_file_descriptors\x18\x03 \x01(\rR\x12maxFileDescriptors\x12#\n" +
	"\rmax_processes\x18\x04 \x01(\rR\fmaxProcesses\x126\n" +
	"\x17max_network_connections\x18\x05 \x01(\rR\x15maxNetworkConnections\"5\n" +
	"\x12EventStreamRequest\x12\x1f\n" +
	"\vevent_types\x18\x01 \x03(\tR\n" +
	"eventTypes\"\xe6\x02\n" +
	"\vKernelEvent\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12F\n" +
	"\x0fprocess_created\x18\n" +
	" \x01(\v2\x1b.kernel.ProcessCreatedEventH\x00R\x0eprocessCreated\x12O\n" +
	"\x12process_terminated\x18\v \x01(\v2\x1e.kernel.ProcessTerminatedEventH\x00R\x11processTerminated\x12I\n" +
	"\x10syscall_executed\x18\f \x01(\v2\x1c.kernel.SyscallExecutedEventH\x00R\x0fsyscallExecuted\x12L\n" +
	"\x11permission_denied\x18\r \x01(\v2\x1d.kernel.PermissionDeniedEventH\x00R\x10permissionDeniedB\a\n" +
	"\x05event\";\n" +
	"\x13ProcessCreatedEvent\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"G\n" +
	"\x16ProcessTerminatedEvent\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\"e\n" +
	"\x14SyscallExecutedEvent\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12!\n" +
	"\fsyscall_type\x18\x02 \x01(\tR\vsyscallType\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"d\n" +
	"\x15PermissionDeniedEvent\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12!\n" +
	"\fsyscall_type\x18\x02 \x01(\tR\vsyscallType\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason*9\n" +
	"\fSandboxLevel\x12\v\n" +
	"\aMINIMAL\x10\x00\x12\f\n" +
	"\bSTANDARD\x10\x01\x12\x0e\n" +
	"\n" +
	"PRIVILEGED\x10\x02*\xf2\x01\n" +
	"\n" +
	"Capability\x12\r\n" +
	"\tREAD_FILE\x10\x00\x12\x0e\n" +
	"\n" +
	"WRITE_FILE\x10\x01\x12\x0f\n" +
	"\vCREATE_FILE\x10\x02\x12\x0f\n" +
	"\vDELETE_FILE\x10\x03\x12\x12\n" +
	"\x0eLIST_DIRECTORY\x10\x04\x12\x11\n" +
	"\rSPAWN_PROCESS\x10\x05\x12\x10\n" +
	"\fKILL_PROCESS\x10\x06\x12\x12\n" +
	"\x0eNETWORK_ACCESS\x10\a\x12\r\n" +
	"\tBIND_PORT\x10\b\x12\x0f\n" +
	"\vSYSTEM_INFO\x10\t\x12\x0f\n" +
	"\vTIME_ACCESS\x10\n" +
	"\x12\x10\n" +
	"\fSEND_MESSAGE\x10\v\x12\x13\n" +
	"\x0fRECEIVE_MESSAGE\x10\f2\xb1\x02\n" +
	"\rKernelService\x12A\n" +
	"\x0eExecuteSyscall\x12\x16.kernel.SyscallRequest\x1a\x17.kernel.SyscallResponse\x12L\n" +
	"\rCreateProcess\x12\x1c.kernel.CreateProcessRequest\x1a\x1d.kernel.CreateProcessResponse\x12L\n" +
	"\rUpdateSandbox\x12\x1c.kernel.UpdateSandboxRequest\x1a\x1d.kernel.UpdateSandboxResponse\x12A\n" +
	"\fStreamEvents\x12\x1a.kernel.EventStreamRequest\x1a\x13.kernel.KernelEvent0\x01B8Z6github.com/GriffinCanCode/AgentOS/backend/proto/kernelb\x06proto3"

var (
	file_kernel_proto_rawDescOnce sync.Once
	file_kernel_proto_rawDescData []byte
)

func file_kernel_proto_rawDescGZIP() []byte {
	file_kernel_proto_rawDescOnce.Do(func() {
		file_kernel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kernel_proto_rawDesc), len(file_kernel_proto_rawDesc)))
	})
	return file_kernel_proto_rawDescData
}

var file_kernel_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_kernel_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_kernel_proto_goTypes = []any{
	(SandboxLevel)(0),              // 0: kernel.SandboxLevel
	(Capability)(0),                // 1: kernel.Capability
	(*SyscallRequest)(nil),         // 2: kernel.SyscallRequest
	(*SyscallResponse)(nil),        // 3: kernel.SyscallResponse
	(*SuccessResult)(nil),          // 4: kernel.SuccessResult
	(*ErrorResult)(nil),            // 5: kernel.ErrorResult
	(*PermissionDeniedResult)(nil), // 6: kernel.PermissionDeniedResult
	(*ReadFileCall)(nil),           // 7: kernel.ReadFileCall
	(*WriteFileCall)(nil),          // 8: kernel.WriteFileCall
	(*CreateFileCall)(nil),         // 9: kernel.CreateFileCall
	(*DeleteFileCall)(nil),         // 10: kernel.DeleteFileCall
	(*ListDirectoryCall)(nil),      // 11: kernel.ListDirectoryCall
	(*FileExistsCall)(nil),         // 12: kernel.FileExistsCall
	(*FileStatCall)(nil),           // 13: kernel.FileStatCall
	(*MoveFileCall)(nil),           // 14: kernel.MoveFileCall
	(*CopyFileCall)(nil),           // 15: kernel.CopyFileCall
	(*CreateDirectoryCall)(nil),    // 16: kernel.CreateDirectoryCall
	(*SpawnProcessCall)(nil),       // 17: kernel.SpawnProcessCall
	(*KillProcessCall)(nil),        // 18: kernel.KillProcessCall
	(*GetSystemInfoCall)(nil),      // 19: kernel.GetSystemInfoCall
	(*GetCurrentTimeCall)(nil),     // 20: kernel.GetCurrentTimeCall
	(*GetEnvVarCall)(nil),          // 21: kernel.GetEnvVarCall
	(*NetworkRequestCall)(nil),     // 22: kernel.NetworkRequestCall
	(*CreateProcessRequest)(nil),   // 23: kernel.CreateProcessRequest
	(*CreateProcessResponse)(nil),  // 24: kernel.CreateProcessResponse
	(*UpdateSandboxRequest)(nil),   // 25: kernel.UpdateSandboxRequest
	(*UpdateSandboxResponse)(nil),  // 26: kernel.UpdateSandboxResponse
	(*ResourceLimits)(nil),         // 27: kernel.ResourceLimits
	(*EventStreamRequest)(nil),     // 28: kernel.EventStreamRequest
	(*KernelEvent)(nil),            // 29: kernel.KernelEvent
	(*ProcessCreatedEvent)(nil),    // 30: kernel.ProcessCreatedEvent
	(*ProcessTerminatedEvent)(nil), // 31: kernel.ProcessTerminatedEvent
	(*SyscallExecutedEvent)(nil),   // 32: kernel.SyscallExecutedEvent
	(*PermissionDeniedEvent)(nil),  // 33: kernel.PermissionDeniedEvent
}
var file_kernel_proto_depIdxs = []int32{
	7,  // 0: kernel.SyscallRequest.read_file:type_name -> kernel.ReadFileCall
	8,  // 1: kernel.SyscallRequest.write_file:type_name -> kernel.WriteFileCall
	9,  // 2: kernel.SyscallRequest.create_file:type_name -> kernel.CreateFileCall
	10, // 3: kernel.SyscallRequest.delete_file:type_name -> kernel.DeleteFileCall
	11, // 4: kernel.SyscallRequest.list_directory:type_name -> kernel.ListDirectoryCall
	12, // 5: kernel.SyscallRequest.file_exists:type_name -> kernel.FileExistsCall
	13, // 6: kernel.SyscallRequest.file_stat:type_name -> kernel.FileStatCall
	14, // 7: kernel.SyscallRequest.move_file:type_name -> kernel.MoveFileCall
	15, // 8: kernel.SyscallRequest.copy_file:type_name -> kernel.CopyFileCall
	16, // 9: kernel.SyscallRequest.create_directory:type_name -> kernel.CreateDirectoryCall
	17, // 10: kernel.SyscallRequest.spawn_process:type_name -> kernel.SpawnProcessCall
	18, // 11: kernel.SyscallRequest.kill_process:type_name -> kernel.KillProcessCall
	19, // 12: kernel.SyscallRequest.get_system_info:type_name -> kernel.GetSystemInfoCall
	20, // 13: kernel.SyscallRequest.get_current_time:type_name -> kernel.GetCurrentTimeCall
	21, // 14: kernel.SyscallRequest.get_env_var:type_name -> kernel.GetEnvVarCall
	22, // 15: kernel.SyscallRequest.network_request:type_name -> kernel.NetworkRequestCall
	4,  // 16: kernel.SyscallResponse.success:type_name -> kernel.SuccessResult
	5,  // 17: kernel.SyscallResponse.error:type_name -> kernel.ErrorResult
	6,  // 18: kernel.SyscallResponse.permission_denied:type_name -> kernel.PermissionDeniedResult
	0,  // 19: kernel.CreateProcessRequest.sandbox_level:type_name -> kernel.SandboxLevel
	1,  // 20: kernel.UpdateSandboxRequest.capabilities:type_name -> kernel.Capability
	27, // 21: kernel.UpdateSandboxRequest.limits:type_name -> kernel.ResourceLimits
	30, // 22: kernel.KernelEvent.process_created:type_name -> kernel.ProcessCreatedEvent
	31, // 23: kernel.KernelEvent.process_terminated:type_name -> kernel.ProcessTerminatedEvent
	32, // 24: kernel.KernelEvent.syscall_executed:type_name -> kernel.SyscallExecutedEvent
	33, // 25: kernel.KernelEvent.permission_denied:type_name -> kernel.PermissionDeniedEvent
	2,  // 26: kernel.KernelService.ExecuteSyscall:input_type -> kernel.SyscallRequest
	23, // 27: kernel.KernelService.CreateProcess:input_type -> kernel.CreateProcessRequest
	25, // 28: kernel.KernelService.UpdateSandbox:input_type -> kernel.UpdateSandboxRequest
	28, // 29: kernel.KernelService.StreamEvents:input_type -> kernel.EventStreamRequest
	3,  // 30: kernel.KernelService.ExecuteSyscall:output_type -> kernel.SyscallResponse
	24, // 31: kernel.KernelService.CreateProcess:output_type -> kernel.CreateProcessResponse
	26, // 32: kernel.KernelService.UpdateSandbox:output_type -> kernel.UpdateSandboxResponse
	29, // 33: kernel.KernelService.StreamEvents:output_type -> kernel.KernelEvent
	30, // [30:34] is the sub-list for method output_type
	26, // [26:30] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_kernel_proto_init() }
func file_kernel_proto_init() {
	if File_kernel_proto != nil {
		return
	}
	file_kernel_proto_msgTypes[0].OneofWrappers = []any{
		(*SyscallRequest_ReadFile)(nil),
		(*SyscallRequest_WriteFile)(nil),
		(*SyscallRequest_CreateFile)(nil),
		(*SyscallRequest_DeleteFile)(nil),
		(*SyscallRequest_ListDirectory)(nil),
		(*SyscallRequest_FileExists)(nil),
		(*SyscallRequest_FileStat)(nil),
		(*SyscallRequest_MoveFile)(nil),
		(*SyscallRequest_CopyFile)(nil),
		(*SyscallRequest_CreateDirectory)(nil),
		(*SyscallRequest_SpawnProcess)(nil),
		(*SyscallRequest_KillProcess)(nil),
		(*SyscallRequest_GetSystemInfo)(nil),
		(*SyscallRequest_GetCurrentTime)(nil),
		(*SyscallRequest_GetEnvVar)(nil),
		(*SyscallRequest_NetworkRequest)(nil),
	}
	file_kernel_proto_msgTypes[1].OneofWrappers = []any{
		(*SyscallResponse_Success)(nil),
		(*SyscallResponse_Error)(nil),
		(*SyscallResponse_PermissionDenied)(nil),
	}
	file_kernel_proto_msgTypes[27].OneofWrappers = []any{
		(*KernelEvent_ProcessCreated)(nil),
		(*KernelEvent_ProcessTerminated)(nil),
		(*KernelEvent_SyscallExecuted)(nil),
		(*KernelEvent_PermissionDenied)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kernel_proto_rawDesc), len(file_kernel_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kernel_proto_goTypes,
		DependencyIndexes: file_kernel_proto_depIdxs,
		EnumInfos:         file_kernel_proto_enumTypes,
		MessageInfos:      file_kernel_proto_msgTypes,
	}.Build()
	File_kernel_proto = out.File
	file_kernel_proto_goTypes = nil
	file_kernel_proto_depIdxs = nil
}
