# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_pb2 as ai__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub(object):
    """AI service for LLM operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateUI = channel.unary_unary(
                '/ai.AIService/GenerateUI',
                request_serializer=ai__pb2.UIRequest.SerializeToString,
                response_deserializer=ai__pb2.UIResponse.FromString,
                _registered_method=True)
        self.StreamChat = channel.unary_stream(
                '/ai.AIService/StreamChat',
                request_serializer=ai__pb2.ChatRequest.SerializeToString,
                response_deserializer=ai__pb2.ChatToken.FromString,
                _registered_method=True)
        self.StreamUI = channel.unary_stream(
                '/ai.AIService/StreamUI',
                request_serializer=ai__pb2.UIRequest.SerializeToString,
                response_deserializer=ai__pb2.UIToken.FromString,
                _registered_method=True)


class AIServiceServicer(object):
    """AI service for LLM operations
    """

    def GenerateUI(self, request, context):
        """Generate UI specification from natural language
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamChat(self, request, context):
        """Stream chat response with thoughts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamUI(self, request, context):
        """Stream UI generation with real-time updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateUI': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateUI,
                    request_deserializer=ai__pb2.UIRequest.FromString,
                    response_serializer=ai__pb2.UIResponse.SerializeToString,
            ),
            'StreamChat': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamChat,
                    request_deserializer=ai__pb2.ChatRequest.FromString,
                    response_serializer=ai__pb2.ChatToken.SerializeToString,
            ),
            'StreamUI': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamUI,
                    request_deserializer=ai__pb2.UIRequest.FromString,
                    response_serializer=ai__pb2.UIToken.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService(object):
    """AI service for LLM operations
    """

    @staticmethod
    def GenerateUI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/GenerateUI',
            ai__pb2.UIRequest.SerializeToString,
            ai__pb2.UIResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai.AIService/StreamChat',
            ai__pb2.ChatRequest.SerializeToString,
            ai__pb2.ChatToken.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamUI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai.AIService/StreamUI',
            ai__pb2.UIRequest.SerializeToString,
            ai__pb2.UIToken.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
